{% set name = "pytorchrl" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pytorch/rl/archive/v{{ version }}.tar.gz
  sha256: 5f255a696ddb658421d6ce3045893d8d49b20f48c0e55f6d24d42f4a3800a9da

build:
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [win]
  rpaths:
    - lib
    - {{ SP_DIR }}/torch/lib

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - wheel
    - pytorch
    - ninja
    - pip
  run:
    - pyvers
    - python
    - pytorch >=2.1.0
    - numpy
    - packaging
    - cloudpickle
    - tensordict >=0.10.0,<0.11.0

test:
  imports:
    - torchrl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytorch/rl
  summary: A modular, primitive-first, python-first PyTorch library for Reinforcement Learning.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
