{% set name = "pytorchrl" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pytorch/rl/archive/v{{ version }}.tar.gz
  sha256: 1dd5c51b7bb175f2a1d69cb565cb239e11ec4a6682015bed50b85929c327c879

build:
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  skip: true  # [win]
  rpaths:
    - lib
    - {{ SP_DIR }}/torch/lib

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - wheel
    - pytorch
    - ninja
    - pip
  run:
    - pyvers
    - python
    - pytorch >=2.1.0
    - numpy
    - packaging
    - cloudpickle
    - tensordict >=0.10.0,<0.11.0

test:
  imports:
    - torchrl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytorch/rl
  summary: A modular, primitive-first, python-first PyTorch library for Reinforcement Learning.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
